//
//  World
//  converzone
//
//  Created by Goga Barabadze on 07.12.18.
//  Copyright © 2018 Goga Barabadze. All rights reserved.
//

import Foundation

let countries_africa = [
    NSLocalizedString("Algeria", comment: "Country"),
    NSLocalizedString("Angola",comment: "Country"),
    NSLocalizedString("Benin",comment: "Country"),
    NSLocalizedString("Botswana",comment: "Country"),
    NSLocalizedString("Burkina Faso",comment: "Country"),
    NSLocalizedString("Burundi",comment: "Country"),
    NSLocalizedString("Cabo Verde",comment: "Country"),
    NSLocalizedString("Cameroon",comment: "Country"),
    NSLocalizedString("Central African Republic",comment: "Country"),
    NSLocalizedString("Chad",comment: "Country"),
    NSLocalizedString("Comoros",comment: "Country"),
    NSLocalizedString("Democratic Republic of the Congo",comment: "Country"),
    NSLocalizedString("Republic of the Congo",comment: "Country"),
    NSLocalizedString("Côte d’Ivoire",comment: "Country"),
    NSLocalizedString("Djibouti",comment: "Country"),
    NSLocalizedString("Egypt",comment: "Country"),
    NSLocalizedString("Equatorial Guinea",comment: "Country"),
    NSLocalizedString("Eritrea",comment: "Country"),
    NSLocalizedString("Eswatini",comment: "Country"),
    NSLocalizedString("Ethiopia",comment: "Country"),
    NSLocalizedString("Gabon",comment: "Country"),
    NSLocalizedString("Gambia",comment: "Country"),
    NSLocalizedString("Ghana",comment: "Country"),
    NSLocalizedString("Guinea",comment: "Country"),
    NSLocalizedString("Guinea-Bissau",comment: "Country"),
    NSLocalizedString("Kenya",comment: "Country"),
    NSLocalizedString("Lesotho",comment: "Country"),
    NSLocalizedString("Liberia",comment: "Country"),
    NSLocalizedString("Libya",comment: "Country"),
    NSLocalizedString("Madagascar",comment: "Country"),
    NSLocalizedString("Malawi",comment: "Country"),
    NSLocalizedString("Mali",comment: "Country"),
    NSLocalizedString("Mauritania",comment: "Country"),
    NSLocalizedString("Mauritius",comment: "Country"),
    NSLocalizedString("Morocco",comment: "Country"),
    NSLocalizedString("Mozambique",comment: "Country"),
    NSLocalizedString("Namibia",comment: "Country"),
    NSLocalizedString("Niger",comment: "Country"),
    NSLocalizedString("Nigeria",comment: "Country"),
    NSLocalizedString("Rwanda",comment: "Country"),
    NSLocalizedString("Sao Tome and Principe",comment: "Country"),
    NSLocalizedString("Senegal",comment: "Country"),
    NSLocalizedString("Seychelles",comment: "Country"),
    NSLocalizedString("Sierra Leone",comment: "Country"),
    NSLocalizedString("Somalia",comment: "Country"),
    NSLocalizedString("South Africa",comment: "Country"),
    NSLocalizedString("South Sudan",comment: "Country"),
    NSLocalizedString("Sudan",comment: "Country"),
    NSLocalizedString("Tanzania",comment: "Country"),
    NSLocalizedString("Togo",comment: "Country"),
    NSLocalizedString("Tunisia",comment: "Country"),
    NSLocalizedString("Uganda",comment: "Country"),
    NSLocalizedString("Zambia",comment: "Country"),
    NSLocalizedString("Zimbabwe", comment: "Country")
]

let countries_asia = [
    NSLocalizedString("Afghanistan",comment: "Country"),
    NSLocalizedString("Armenia",comment: "Country"),
    NSLocalizedString("Azerbaijan",comment: "Country"),
    NSLocalizedString("Bahrain",comment: "Country"),
    NSLocalizedString("Bangladesh",comment: "Country"),
    NSLocalizedString("Bhutan",comment: "Country"),
    NSLocalizedString("Brunei",comment: "Country"),
    NSLocalizedString("Cambodia",comment: "Country"),
    NSLocalizedString("China",comment: "Country"),
    NSLocalizedString("Georgia",comment: "Country"),
    NSLocalizedString("India",comment: "Country"),
    NSLocalizedString("Indonesia",comment: "Country"),
    NSLocalizedString("Iran",comment: "Country"),
    NSLocalizedString("Iraq",comment: "Country"),
    NSLocalizedString("Israel",comment: "Country"),
    NSLocalizedString("Japan",comment: "Country"),
    NSLocalizedString("Jordan",comment: "Country"),
    NSLocalizedString("Kazakhstan",comment: "Country"),
    NSLocalizedString("Kuwait",comment: "Country"),
    NSLocalizedString("Kyrgyzstan",comment: "Country"),
    NSLocalizedString("Laos",comment: "Country"),
    NSLocalizedString("Lebanon",comment: "Country"),
    NSLocalizedString("Malaysia",comment: "Country"),
    NSLocalizedString("Maldives",comment: "Country"),
    NSLocalizedString("Mongolia",comment: "Country"),
    NSLocalizedString("Myanmar",comment: "Country"),
    NSLocalizedString("Nepal",comment: "Country"),
    NSLocalizedString("North Korea",comment: "Country"),
    NSLocalizedString("Oman",comment: "Country"),
    NSLocalizedString("Pakistan",comment: "Country"),
    NSLocalizedString("Palestine",comment: "Country"),
    NSLocalizedString("Philippines",comment: "Country"),
    NSLocalizedString("Qatar",comment: "Country"),
    NSLocalizedString("Russia",comment: "Country"),
    NSLocalizedString("Saudi Arabia",comment: "Country"),
    NSLocalizedString("Singapore",comment: "Country"),
    NSLocalizedString("South Korea",comment: "Country"),
    NSLocalizedString("Sri Lanka",comment: "Country"),
    NSLocalizedString("Syria",comment: "Country"),
    NSLocalizedString("Taiwan",comment: "Country"),
    NSLocalizedString("Tajikistan",comment: "Country"),
    NSLocalizedString("Thailand",comment: "Country"),
    NSLocalizedString("Timor-Leste",comment: "Country"),
    NSLocalizedString("Turkey",comment: "Country"),
    NSLocalizedString("Turkmenistan",comment: "Country"),
    NSLocalizedString("United Arab Emirates",comment: "Country"),
    NSLocalizedString("Uzbekistan",comment: "Country"),
    NSLocalizedString("Vietnam",comment: "Country"),
    NSLocalizedString("Yemen", comment: "Country")
]

let countries_australia_and_oceania = [
    NSLocalizedString("Australia",comment: "Country"),
    NSLocalizedString("Fiji",comment: "Country"),
    NSLocalizedString("Kiribati",comment: "Country"),
    NSLocalizedString("Marshall Islands",comment: "Country"),
    NSLocalizedString("Micronesia",comment: "Country"),
    NSLocalizedString("Nauru",comment: "Country"),
    NSLocalizedString("New Zealand",comment: "Country"),
    NSLocalizedString("Palau",comment: "Country"),
    NSLocalizedString("Papua New Guinea",comment: "Country"),
    NSLocalizedString("Samoa",comment: "Country"),
    NSLocalizedString("Solomon Islands",comment: "Country"),
    NSLocalizedString("Tonga",comment: "Country"),
    NSLocalizedString("Tuvalu",comment: "Country"),
    NSLocalizedString("Vanuatu", comment: "Country")
]

let countries_europe = [
    NSLocalizedString("Albania",comment: "Country"),
    NSLocalizedString("Andorra",comment: "Country"),
    NSLocalizedString("Armenia",comment: "Country"),
    NSLocalizedString("Austria",comment: "Country"),
    NSLocalizedString("Azerbaijan",comment: "Country"),
    NSLocalizedString("Belarus",comment: "Country"),
    NSLocalizedString("Belgium",comment: "Country"),
    NSLocalizedString("Bosnia and Herzegovina",comment: "Country"),
    NSLocalizedString("Bulgaria",comment: "Country"),
    NSLocalizedString("Croatia",comment: "Country"),
    NSLocalizedString("Cyprus",comment: "Country"),
    NSLocalizedString("Czech Republic",comment: NSLocalizedString("Country", comment: "")),
    NSLocalizedString("Denmark",comment: "Country"),
    NSLocalizedString("Estonia",comment: "Country"),
    NSLocalizedString("Finland",comment: "Country"),
    NSLocalizedString("France",comment: "Country"),
    NSLocalizedString("Georgia",comment: "Country"),
    NSLocalizedString("Germany",comment: "Country"),
    NSLocalizedString("Greece",comment: "Country"),
    NSLocalizedString("Hungary",comment: "Country"),
    NSLocalizedString("Iceland",comment: "Country"),
    NSLocalizedString("Ireland",comment: "Country"),
    NSLocalizedString("Italy",comment: "Country"),
    NSLocalizedString("Kazakhstan",comment: "Country"),
    NSLocalizedString("Kosovo",comment: "Country"),
    NSLocalizedString("Latvia",comment: "Country"),
    NSLocalizedString("Liechtenstein",comment: "Country"),
    NSLocalizedString("Lithuania",comment: "Country"),
    NSLocalizedString("Luxembourg",comment: "Country"),
    NSLocalizedString("Republic of Macedonia",comment: "Country"),
    NSLocalizedString("Malta",comment: "Country"),
    NSLocalizedString("Moldova",comment: "Country"),
    NSLocalizedString("Monaco",comment: "Country"),
    NSLocalizedString("Montenegro",comment: "Country"),
    NSLocalizedString("Netherlands",comment: "Country"),
    NSLocalizedString("Norway",comment: "Country"),
    NSLocalizedString("Republic of Poland", comment: "Country"),
    NSLocalizedString("Portugal", comment: "Country"),
    NSLocalizedString("Romania",comment: "Country"),
    NSLocalizedString("Russia",comment: "Country"),
    NSLocalizedString("San Marino",comment: "Country"),
    NSLocalizedString("Serbia",comment: "Country"),
    NSLocalizedString("Slovakia",comment: "Country"),
    NSLocalizedString("Slovenia",comment: "Country"),
    NSLocalizedString("Spain",comment: "Country"),
    NSLocalizedString("Sweden",comment: "Country"),
    NSLocalizedString("Switzerland",comment: "Country"),
    NSLocalizedString("Turkey",comment: "Country"),
    NSLocalizedString("Ukraine",comment: "Country"),
    NSLocalizedString("United Kingdom",comment: "Country"),
    NSLocalizedString("Vatican City", comment: "Country")
]

let countries_north_america = [
    NSLocalizedString("Antigua and Barbuda",comment: "Country"),
    NSLocalizedString("Bahamas",comment: "Country"),
    NSLocalizedString("Barbados",comment: "Country"),
    NSLocalizedString("Belize",comment: "Country"),
    NSLocalizedString("Canada",comment: "Country"),
    NSLocalizedString("Costa Rica",comment: "Country"),
    NSLocalizedString("Cuba",comment: "Country"),
    NSLocalizedString("Dominica",comment: "Country"),
    NSLocalizedString("Dominican Republic",comment: "Country"),
    NSLocalizedString("El Salvador",comment: "Country"),
    NSLocalizedString("Grenada",comment: "Country"),
    NSLocalizedString("Guatemala",comment: "Country"),
    NSLocalizedString("Haiti",comment: "Country"),
    NSLocalizedString("Honduras",comment: "Country"),
    NSLocalizedString("Jamaica",comment: "Country"),
    NSLocalizedString("Mexico",comment: "Country"),
    NSLocalizedString("Nicaragua",comment: "Country"),
    NSLocalizedString("Panama",comment: "Country"),
    NSLocalizedString("Saint Kitts and Nevis",comment: "Country"),
    NSLocalizedString("Saint Lucia",comment: "Country"),
    NSLocalizedString("Saint Vincent and the Grenadines",comment: "Country"),
    NSLocalizedString("Trinidad and Tobago",comment: "Country"),
    NSLocalizedString("United States of America", comment: "Country"),
]

let countries_south_america = [
    NSLocalizedString("Argentina",comment: "Country"),
    NSLocalizedString("Bolivia",comment: "Country"),
    NSLocalizedString("Brazil",comment: "Country"),
    NSLocalizedString("Chile",comment: "Country"),
    NSLocalizedString("Colombia",comment: "Country"),
    NSLocalizedString("Ecuador",comment: "Country"),
    NSLocalizedString("Guyana",comment: "Country"),
    NSLocalizedString("Paraguay",comment: "Country"),
    NSLocalizedString("Peru",comment: "Country"),
    NSLocalizedString("Suriname",comment: "Country"),
    NSLocalizedString("Uruguay",comment: "Country"),
    NSLocalizedString("Venezuela", comment: "Country")
]

let all_languages = [
    NSLocalizedString("Abaza", comment: "Language"),
    NSLocalizedString("Abenaki", comment: "Language"),
    NSLocalizedString("Abkhaz", comment: "Language"),
    NSLocalizedString("Abui", comment: "Language"),
    NSLocalizedString("Achang", comment: "Language"),
    NSLocalizedString("Acehnese", comment: "Language"),
    NSLocalizedString("Acheron", comment: "Language"),
    NSLocalizedString("Achi", comment: "Language"),
    NSLocalizedString("Acholi", comment: "Language"),
    NSLocalizedString("Achuar-Shiwiar", comment: "Language"),
    NSLocalizedString("Achumawi", comment: "Language"),
    NSLocalizedString("Adaizan", comment: "Language"),
    NSLocalizedString("Adamaua Fulfulde", comment: "Language"),
    NSLocalizedString("Adyghe", comment: "Language"),
    NSLocalizedString("Adzera", comment: "Language"),
    NSLocalizedString("Afar", comment: "Language"),
    NSLocalizedString("Afrikaans", comment: "Language"),
    NSLocalizedString("Aghul", comment: "Language"),
    NSLocalizedString("Aguacateco", comment: "Language"),
    NSLocalizedString("Aguaruna", comment: "Language"),
    NSLocalizedString("Ahom", comment: "Language"),
    NSLocalizedString("Ainu", comment: "Language"),
    NSLocalizedString("Ajië", comment: "Language"),
    NSLocalizedString("Akan", comment: "Language"),
    NSLocalizedString("Akhvakh", comment: "Language"),
    NSLocalizedString("Akkadian", comment: "Language"),
    NSLocalizedString("Aklan", comment: "Language"),
    NSLocalizedString("Akurio", comment: "Language"),
    NSLocalizedString("Alabama", comment: "Language"),
    NSLocalizedString("Albanian", comment: "Language"),
    NSLocalizedString("Aleut", comment: "Language"),
    NSLocalizedString("Algonquin", comment: "Language"),
    NSLocalizedString("Alsatian", comment: "Language"),
    NSLocalizedString("Altay", comment: "Language"),
    NSLocalizedString("Alur", comment: "Language"),
    NSLocalizedString("Amahuaca", comment: "Language"),
    NSLocalizedString("Amarakaeri", comment: "Language"),
    NSLocalizedString("Amarasi", comment: "Language"),
    NSLocalizedString("Amele", comment: "Language"),
    NSLocalizedString("Amharic", comment: "Language"),
    NSLocalizedString("Amis", comment: "Language"),
    NSLocalizedString("Andi", comment: "Language"),
    NSLocalizedString("Andoa", comment: "Language"),
    NSLocalizedString("Angami", comment: "Language"),
    NSLocalizedString("Anuki", comment: "Language"),
    NSLocalizedString("Anutan", comment: "Language"),
    NSLocalizedString("Apache", comment: "Language"),
    NSLocalizedString("Apma", comment: "Language"),
    NSLocalizedString("Arabela", comment: "Language"),
    NSLocalizedString("Arabic (Algerian)", comment: "Language"),
    NSLocalizedString("Arabic (Cypriot)", comment: "Language"),
    NSLocalizedString("Arabic (Egyptian)", comment: "Language"),
    NSLocalizedString("Arabic (Lebanese)", comment: "Language"),
    NSLocalizedString("Arabic (Modern Standard)", comment: "Language"),
    NSLocalizedString("Arabic (Moroccan)", comment: "Language"),
    NSLocalizedString("Arabic (Syrian)", comment: "Language"),
    NSLocalizedString("Arabic (Tunisian)", comment: "Language"),
    NSLocalizedString("Aragonese", comment: "Language"),
    NSLocalizedString("Arakanese", comment: "Language"),
    NSLocalizedString("Araki", comment: "Language"),
    NSLocalizedString("Aramaic (Ancient)", comment: "Language"),
    NSLocalizedString("Aramaic (Syriac)", comment: "Language"),
    NSLocalizedString("Aramaic (Neo-)", comment: "Language"),
    NSLocalizedString("Aranese", comment: "Language"),
    NSLocalizedString("Arapaho", comment: "Language"),
    NSLocalizedString("Arawak", comment: "Language"),
    NSLocalizedString("Arbëresh", comment: "Language"),
    NSLocalizedString("Archi", comment: "Language"),
    NSLocalizedString("Argobba", comment: "Language"),
    NSLocalizedString("Are", comment: "Language"),
    NSLocalizedString("Arikara", comment: "Language"),
    NSLocalizedString("Aringa", comment: "Language"),
    NSLocalizedString("Armenian", comment: "Language"),
    NSLocalizedString("Aromanian (Vlach)", comment: "Language"),
    NSLocalizedString("Arrernte", comment: "Language"),
    NSLocalizedString("Arvanitic", comment: "Language"),
    NSLocalizedString("Asháninka", comment: "Language"),
    NSLocalizedString("Ashéninka", comment: "Language"),
    NSLocalizedString("Assamese", comment: "Language"),
    NSLocalizedString("Assiniboine", comment: "Language"),
    NSLocalizedString("Assyrian(Neo-)", comment: "Language"),
    NSLocalizedString("Asturian", comment: "Language"),
    NSLocalizedString("Atayal", comment: "Language"),
    NSLocalizedString("Atikamekw", comment: "Language"),
    NSLocalizedString("Auhelawa", comment: "Language"),
    NSLocalizedString("Avar", comment: "Language"),
    NSLocalizedString("Avestan", comment: "Language"),
    NSLocalizedString("Avokaya", comment: "Language"),
    NSLocalizedString("Awadhi", comment: "Language"),
    NSLocalizedString("Awara", comment: "Language"),
    NSLocalizedString("Awing", comment: "Language"),
    NSLocalizedString("Awngi", comment: "Language"),
    NSLocalizedString("Aymara", comment: "Language"),
    NSLocalizedString("Äynu", comment: "Language"),
    NSLocalizedString("Azerbaijani", comment: "Language"),
    NSLocalizedString("Babine-Witsuwit'en", comment: "Language"),
    NSLocalizedString("Badaga", comment: "Language"),
    NSLocalizedString("Bagatha", comment: "Language"),
    NSLocalizedString("Bagvalal", comment: "Language"),
    NSLocalizedString("Bai", comment: "Language"),
    NSLocalizedString("Baka", comment: "Language"),
    NSLocalizedString("Balinese", comment: "Language"),
    NSLocalizedString("Balkar (Karachay-Balkar)", comment: "Language"),
    NSLocalizedString("Balti", comment: "Language"),
    NSLocalizedString("Baluchi", comment: "Language"),
    NSLocalizedString("Bambara", comment: "Language"),
    NSLocalizedString("Bamum", comment: "Language"),
    NSLocalizedString("Baniwa", comment: "Language"),
    NSLocalizedString("Bantawa", comment: "Language"),
    NSLocalizedString("Barai", comment: "Language"),
    NSLocalizedString("Bari", comment: "Language"),
    NSLocalizedString("Bartangi", comment: "Language"),
    NSLocalizedString("Bashkir", comment: "Language"),
    NSLocalizedString("Basque", comment: "Language"),
    NSLocalizedString("Bassa", comment: "Language"),
    NSLocalizedString("Batak Dairi", comment: "Language"),
    NSLocalizedString("Batak Karo", comment: "Language"),
    NSLocalizedString("Batak Mandailing", comment: "Language"),
    NSLocalizedString("Batak Simalungun", comment: "Language"),
    NSLocalizedString("Batak Toba", comment: "Language"),
    NSLocalizedString("Batsbi", comment: "Language"),
    NSLocalizedString("Bavarian", comment: "Language"),
    NSLocalizedString("Beaver", comment: "Language"),
    NSLocalizedString("Beja", comment: "Language"),
    NSLocalizedString("Belarusian", comment: "Language"),
    NSLocalizedString("Beli", comment: "Language"),
    NSLocalizedString("Bemba", comment: "Language"),
    NSLocalizedString("Bench", comment: "Language"),
    NSLocalizedString("Bengali", comment: "Language"),
    NSLocalizedString("Bezhta", comment: "Language"),
    NSLocalizedString("Bhojpuri", comment: "Language"),
    NSLocalizedString("Biete", comment: "Language"),
    NSLocalizedString("Bikol", comment: "Language"),
    NSLocalizedString("Biloxi", comment: "Language"),
    NSLocalizedString("Bima", comment: "Language"),
    NSLocalizedString("Bislama", comment: "Language"),
    NSLocalizedString("Bisu", comment: "Language"),
    NSLocalizedString("Blackfoot", comment: "Language"),
    NSLocalizedString("Blagar", comment: "Language"),
    NSLocalizedString("Blin", comment: "Language"),
    NSLocalizedString("Bodo", comment: "Language"),
    NSLocalizedString("Bokar", comment: "Language"),
    NSLocalizedString("Bolinao", comment: "Language"),
    NSLocalizedString("Bongo", comment: "Language"),
    NSLocalizedString("Bora", comment: "Language"),
    NSLocalizedString("Bosnian", comment: "Language"),
    NSLocalizedString("Botlikh", comment: "Language"),
    NSLocalizedString("Bouyei", comment: "Language"),
    NSLocalizedString("Breton", comment: "Language"),
    NSLocalizedString("Budukh", comment: "Language"),
    NSLocalizedString("Buginese", comment: "Language"),
    NSLocalizedString("Buhid", comment: "Language"),
    NSLocalizedString("Buhutu", comment: "Language"),
    NSLocalizedString("Bulgarian", comment: "Language"),
    NSLocalizedString("Bundjalung", comment: "Language"),
    NSLocalizedString("Burmese", comment: "Language"),
    NSLocalizedString("Burushaski", comment: "Language"),
    NSLocalizedString("Buryat", comment: "Language"),
    NSLocalizedString("Busa", comment: "Language"),
    NSLocalizedString("Bushi", comment: "Language"),
    NSLocalizedString("Bhutanese", comment: "Language"),
    NSLocalizedString("Carrier", comment: "Language"),
    NSLocalizedString("Catalan", comment: "Language"),
    NSLocalizedString("Cayuga", comment: "Language"),
    NSLocalizedString("Cebuano", comment: "Language"),
    NSLocalizedString("Central Dusun", comment: "Language"),
    NSLocalizedString("Chagatai", comment: "Language"),
    NSLocalizedString("Chaha", comment: "Language"),
    NSLocalizedString("Chamorro", comment: "Language"),
    NSLocalizedString("Chechen", comment: "Language"),
    NSLocalizedString("Cherokee", comment: "Language"),
    NSLocalizedString("Cheyenne", comment: "Language"),
    NSLocalizedString("Chichewa", comment: "Language"),
    NSLocalizedString("Chickasaw", comment: "Language"),
    NSLocalizedString("Chinese", comment: "Language"),
    NSLocalizedString("Chinese (Cantonese)",comment: "Language"),
    NSLocalizedString("Chinese (Dungan)", comment: "Language"),
    NSLocalizedString("Chinese (Gan)", comment: "Language"),
    NSLocalizedString("Chinese (Hakka)", comment: "Language"),
    NSLocalizedString("Chinese (Mandarin)", comment: "Language"),
    NSLocalizedString("Chinese (Shanghainese)", comment: "Language"),
    NSLocalizedString("Chinese (Taiwanese)", comment: "Language"),
    NSLocalizedString("Chinese (Teochew)", comment: "Language"),
    NSLocalizedString("Chinese (Xiang)", comment: "Language"),
    NSLocalizedString("Chipewyan", comment: "Language"),
    NSLocalizedString("Choctaw", comment: "Language"),
    NSLocalizedString("Coastal Kadazan", comment: "Language"),
    NSLocalizedString("Comanche", comment: "Language"),
    NSLocalizedString("Cornish", comment: "Language"),
    NSLocalizedString("Corsican", comment: "Language"),
    NSLocalizedString("Cree", comment: "Language"),
    NSLocalizedString("Creek", comment: "Language"),
    NSLocalizedString("Croatian", comment: "Language"),
    NSLocalizedString("Czech", comment: "Language"),
    NSLocalizedString("Dakota", comment: "Language"),
    NSLocalizedString("Dangme", comment: "Language"),
    NSLocalizedString("Danish", comment: "Language"),
    NSLocalizedString("Dargwa", comment: "Language"),
    NSLocalizedString("Dari", comment: "Language"),
    NSLocalizedString("Dinka", comment: "Language"),
    NSLocalizedString("Ditidaht", comment: "Language"),
    NSLocalizedString("Dungan", comment: "Language"),
    NSLocalizedString("Dutch", comment: "Language"),
    NSLocalizedString("Dzongkha (Bhutanese)", comment: "Language"),
    NSLocalizedString("English", comment: "Language"),
    NSLocalizedString("English (Old) / Anglo-Saxon", comment: "Language"),
    NSLocalizedString("Erzya", comment: "Language"),
    NSLocalizedString("Estonian", comment: "Language"),
    NSLocalizedString("Esperanto", comment: "Language"),
    NSLocalizedString("Ewe", comment: "Language"),
    NSLocalizedString("Eyak", comment: "Language"),
    NSLocalizedString("Faroese", comment: "Language"),
    NSLocalizedString("Fijian", comment: "Language"),
    NSLocalizedString("Finnish", comment: "Language"),
    NSLocalizedString("Flemish", comment: "Language"),
    NSLocalizedString("Fon", comment: "Language"),
    NSLocalizedString("French", comment: "Language"),
    NSLocalizedString("Frisian (North)", comment: "Language"),
    NSLocalizedString("Frisian (West)", comment: "Language"),
    NSLocalizedString("Friulan", comment: "Language"),
    NSLocalizedString("Fula", comment: "Language"),
    NSLocalizedString("Ga", comment: "Language"),
    NSLocalizedString("Galician", comment: "Language"),
    NSLocalizedString("Ganda", comment: "Language"),
    NSLocalizedString("Ge'ez", comment: "Language"),
    NSLocalizedString("Genoese", comment: "Language"),
    NSLocalizedString("Georgian", comment: "Language"),
    NSLocalizedString("German", comment: "Language"),
    NSLocalizedString("Godoberi", comment: "Language"),
    NSLocalizedString("Gooniyandi", comment: "Language"),
    NSLocalizedString("Greek", comment: "Language"),
    NSLocalizedString("Greenlandic", comment: "Language"),
    NSLocalizedString("Guernsey Norman", comment: "Language"),
    NSLocalizedString("Guarani", comment: "Language"),
    NSLocalizedString("Gujarati", comment: "Language"),
    NSLocalizedString("Gwich'in", comment: "Language"),
    NSLocalizedString("Haida", comment: "Language"),
    NSLocalizedString("Haitian Creole", comment: "Language"),
    NSLocalizedString("Hän", comment: "Language"),
    NSLocalizedString("Harari", comment: "Language"),
    NSLocalizedString("Hausa", comment: "Language"),
    NSLocalizedString("Hawaiian", comment: "Language"),
    NSLocalizedString("Hebrew", comment: "Language"),
    NSLocalizedString("Herero", comment: "Language"),
    NSLocalizedString("Hindi", comment: "Language"),
    NSLocalizedString("Huambisa", comment: "Language"),
    NSLocalizedString("Hungarian", comment: "Language"),
    NSLocalizedString("Icelandic", comment: "Language"),
    NSLocalizedString("Igbo", comment: "Language"),
    NSLocalizedString("Ilocano", comment: "Language"),
    NSLocalizedString("Indonesian", comment: "Language"),
    NSLocalizedString("Ingush", comment: "Language"),
    NSLocalizedString("Inuktitut", comment: "Language"),
    NSLocalizedString("Iñupiaq", comment: "Language"),
    NSLocalizedString("Irish (Gaelic)", comment: "Language"),
    NSLocalizedString("Italian", comment: "Language"),
    NSLocalizedString("Japanese", comment: "Language"),
    NSLocalizedString("Javanese", comment: "Language"),
    NSLocalizedString("Jersey Norman", comment: "Language"),
    NSLocalizedString("Kabardian", comment: "Language"),
    NSLocalizedString("Kabyle", comment: "Language"),
    NSLocalizedString("Kadazandusun", comment: "Language"),
    NSLocalizedString("Kaingang", comment: "Language"),
    NSLocalizedString("Kannada", comment: "Language"),
    NSLocalizedString("Kanuri", comment: "Language"),
    NSLocalizedString("Kapampangan", comment: "Language"),
    NSLocalizedString("Karakalpak", comment: "Language"),
    NSLocalizedString("Karelian", comment: "Language"),
    NSLocalizedString("Kashmiri", comment: "Language"),
    NSLocalizedString("Kashubian", comment: "Language"),
    NSLocalizedString("Kawaiisu", comment: "Language"),
    NSLocalizedString("Kazakh", comment: "Language"),
    NSLocalizedString("Khakas", comment: "Language"),
    NSLocalizedString("Khmer", comment: "Language"),
    NSLocalizedString("Khoekhoe", comment: "Language"),
    NSLocalizedString("Kikuyu", comment: "Language"),
    NSLocalizedString("Kinyarwanda", comment: "Language"),
    NSLocalizedString("Kiribati", comment: "Language"),
    NSLocalizedString("Kirundi", comment: "Language"),
    NSLocalizedString("Komi", comment: "Language"),
    NSLocalizedString("Kongo", comment: "Language"),
    NSLocalizedString("Konkani", comment: "Language"),
    NSLocalizedString("Korean", comment: "Language"),
    NSLocalizedString("Kumyk", comment: "Language"),
    NSLocalizedString("Kurdish", comment: "Language"),
    NSLocalizedString("Kven", comment: "Language"),
    NSLocalizedString("Kwanyama", comment: "Language"),
    NSLocalizedString("Kyrgyz", comment: "Language"),
    NSLocalizedString("Ladin", comment: "Language"),
    NSLocalizedString("Ladino", comment: "Language"),
    NSLocalizedString("Lahnda", comment: "Language"),
    NSLocalizedString("Lakota", comment: "Language"),
    NSLocalizedString("Lao", comment: "Language"),
    NSLocalizedString("Latin", comment: "Language"),
    NSLocalizedString("Latvian", comment: "Language"),
    NSLocalizedString("Laz", comment: "Language"),
    NSLocalizedString("Lezgian", comment: "Language"),
    NSLocalizedString("Limburgish", comment: "Language"),
    NSLocalizedString("Lingala", comment: "Language"),
    NSLocalizedString("Lithuanian", comment: "Language"),
    NSLocalizedString("Livonian", comment: "Language"),
    NSLocalizedString("Lombard", comment: "Language"),
    NSLocalizedString("Low German/Low Saxon", comment: "Language"),
    NSLocalizedString("Luo", comment: "Language"),
    NSLocalizedString("Luxembourgish", comment: "Language"),
    NSLocalizedString("Maasai/Maa", comment: "Language"),
    NSLocalizedString("Macedonian", comment: "Language"),
    NSLocalizedString("Maldivian", comment: "Language"),
    NSLocalizedString("Maithili", comment: "Language"),
    NSLocalizedString("Makah", comment: "Language"),
    NSLocalizedString("Malagasy", comment: "Language"),
    NSLocalizedString("Malay", comment: "Language"),
    NSLocalizedString("Malayalam", comment: "Language"),
    NSLocalizedString("Maltese", comment: "Language"),
    NSLocalizedString("Mandinka", comment: "Language"),
    NSLocalizedString("Manipuri", comment: "Language"),
    NSLocalizedString("Mansi", comment: "Language"),
    NSLocalizedString("Manx", comment: "Language"),
    NSLocalizedString("Māori", comment: "Language"),
    NSLocalizedString("Marathi", comment: "Language"),
    NSLocalizedString("Mari/Cheremis", comment: "Language"),
    NSLocalizedString("Marshallese", comment: "Language"),
    NSLocalizedString("Menominee", comment: "Language"),
    NSLocalizedString("Mirandese", comment: "Language"),
    NSLocalizedString("Mohawk", comment: "Language"),
    NSLocalizedString("Moksha", comment: "Language"),
    NSLocalizedString("Moldovan", comment: "Language"),
    NSLocalizedString("Mongolian", comment: "Language"),
    NSLocalizedString("Montagnais", comment: "Language"),
    NSLocalizedString("Nahuatl", comment: "Language"),
    NSLocalizedString("Naskapi", comment: "Language"),
    NSLocalizedString("Nauruan", comment: "Language"),
    NSLocalizedString("Navajo", comment: "Language"),
    NSLocalizedString("Occitan", comment: "Language"),
    NSLocalizedString("Oshiwambo", comment: "Language"),
    NSLocalizedString("Nepali", comment: "Language"),
    NSLocalizedString("Newari", comment: "Language"),
    NSLocalizedString("Niuean", comment: "Language"),
    NSLocalizedString("Nogai", comment: "Language"),
    NSLocalizedString("Noongar", comment: "Language"),
    NSLocalizedString("Northern Sotho", comment: "Language"),
    NSLocalizedString("Norwegian", comment: "Language"),
    NSLocalizedString("Nyamwezi", comment: "Language"),
    NSLocalizedString("Nyoro", comment: "Language"),
    NSLocalizedString("Odia", comment: "Language"),
    NSLocalizedString("Ojibwe", comment: "Language"),
    NSLocalizedString("Old English", comment: "Language"),
    NSLocalizedString("Old Norse", comment: "Language"),
    NSLocalizedString("O'odham", comment: "Language"),
    NSLocalizedString("Oromo", comment: "Language"),
    NSLocalizedString("Ossetian", comment: "Language"),
    NSLocalizedString("Palauan", comment: "Language"),
    NSLocalizedString("Pali", comment: "Language"),
    NSLocalizedString("Papiamento", comment: "Language"),
    NSLocalizedString("Pashto", comment: "Language"),
    NSLocalizedString("Persian", comment: "Language"),
    NSLocalizedString("Piedmontese", comment: "Language"),
    NSLocalizedString("Polish", comment: "Language"),
    NSLocalizedString("Portuguese", comment: "Language"),
    NSLocalizedString("Punjabi", comment: "Language"),
    NSLocalizedString("Quechua", comment: "Language"),
    NSLocalizedString("Raga", comment: "Language"),
    NSLocalizedString("Rapanui", comment: "Language"),
    NSLocalizedString("Rarotongan", comment: "Language"),
    NSLocalizedString("Romanian", comment: "Language"),
    NSLocalizedString("Romansh", comment: "Language"),
    NSLocalizedString("Romani", comment: "Language"),
    NSLocalizedString("Rotuman", comment: "Language"),
    NSLocalizedString("Russian", comment: "Language"),
    NSLocalizedString("Ruthenian", comment: "Language"),
    NSLocalizedString("Saami (Inari)", comment: "Language"),
    NSLocalizedString("Sámi (Kildin)", comment: "Language"),
    NSLocalizedString("Sámi (Lule)", comment: "Language"),
    NSLocalizedString("Sámi (North)", comment: "Language"),
    NSLocalizedString("Sámi (Pite)", comment: "Language"),
    NSLocalizedString("Sámi (Skolt)", comment: "Language"),
    NSLocalizedString("Sámi (South)", comment: "Language"),
    NSLocalizedString("Sámi (Ter)", comment: "Language"),
    NSLocalizedString("Sámi (Ume)", comment: "Language"),
    NSLocalizedString("Santali", comment: "Language"),
    NSLocalizedString("Samoan", comment: "Language"),
    NSLocalizedString("Sango", comment: "Language"),
    NSLocalizedString("Sanskrit", comment: "Language"),
    NSLocalizedString("Sardinian", comment: "Language"),
    NSLocalizedString("Sark Norman", comment: "Language"),
    NSLocalizedString("Scots", comment: "Language"),
    NSLocalizedString("Scottish Gaelic", comment: "Language"),
    NSLocalizedString("Selkup", comment: "Language"),
    NSLocalizedString("Serbian", comment: "Language"),
    NSLocalizedString("Shavante", comment: "Language"),
    NSLocalizedString("Shawnee", comment: "Language"),
    NSLocalizedString("Shona", comment: "Language"),
    NSLocalizedString("Shor", comment: "Language"),
    NSLocalizedString("Sicilian", comment: "Language"),
    NSLocalizedString("Sidamo", comment: "Language"),
    NSLocalizedString("Silesian", comment: "Language"),
    NSLocalizedString("Sindhi", comment: "Language"),
    NSLocalizedString("Sinhala", comment: "Language"),
    NSLocalizedString("Silt'e", comment: "Language"),
    NSLocalizedString("Slovak", comment: "Language"),
    NSLocalizedString("Slovenian", comment: "Language"),
    NSLocalizedString("Somali", comment: "Language"),
    NSLocalizedString("Soninke", comment: "Language"),
    NSLocalizedString("Sorbian (Lower)", comment: "Language"),
    NSLocalizedString("Sorbian (Upper)", comment: "Language"),
    NSLocalizedString("Southern Sotho", comment: "Language"),
    NSLocalizedString("South Slavey", comment: "Language"),
    NSLocalizedString("Spanish", comment: "Language"),
    NSLocalizedString("Sundanese", comment: "Language"),
    NSLocalizedString("Svan", comment: "Language"),
    NSLocalizedString("Swabish", comment: "Language"),
    NSLocalizedString("Swahili", comment: "Language"),
    NSLocalizedString("Swati", comment: "Language"),
    NSLocalizedString("Swedish", comment: "Language"),
    NSLocalizedString("Swiss German", comment: "Language"),
    NSLocalizedString("Sylheti", comment: "Language"),
    NSLocalizedString("Syriac", comment: "Language"),
    NSLocalizedString("Tabassaran", comment: "Language"),
    NSLocalizedString("Tagalog", comment: "Language"),
    NSLocalizedString("Tahitian", comment: "Language"),
    NSLocalizedString("Tai Nüa", comment: "Language"),
    NSLocalizedString("Tajik", comment: "Language"),
    NSLocalizedString("Tamahaq", comment: "Language"),
    NSLocalizedString("Tamasheq", comment: "Language"),
    NSLocalizedString("Tamazight", comment: "Language"),
    NSLocalizedString("Tamil", comment: "Language"),
    NSLocalizedString("Tatar", comment: "Language"),
    NSLocalizedString("Telugu", comment: "Language"),
    NSLocalizedString("Tetum", comment: "Language"),
    NSLocalizedString("Thai", comment: "Language"),
    NSLocalizedString("Tibetan", comment: "Language"),
    NSLocalizedString("Tigre", comment: "Language"),
    NSLocalizedString("Tigrinya", comment: "Language"),
    
    NSLocalizedString("Tlingit", comment: "Language"),
    NSLocalizedString("Tok Pisin", comment: "Language"),
    NSLocalizedString("Tonga", comment: "Language"),
    NSLocalizedString("Tongan", comment: "Language"),
    NSLocalizedString("Torwali", comment: "Language"),
    NSLocalizedString("Tsez", comment: "Language"),
    NSLocalizedString("Tsonga", comment: "Language"),
    NSLocalizedString("Tswana", comment: "Language"),
    NSLocalizedString("Tumbuka", comment: "Language"),
    NSLocalizedString("Turkish", comment: "Language"),
    NSLocalizedString("Turkmen", comment: "Language"),
    NSLocalizedString("Tuscarora", comment: "Language"),
    NSLocalizedString("Tuvaluan", comment: "Language"),
    NSLocalizedString("Tuvan", comment: "Language"),
    NSLocalizedString("Twi", comment: "Language"),
    NSLocalizedString("Udmurt", comment: "Language"),
    NSLocalizedString("Ukrainian", comment: "Language"),
    NSLocalizedString("Urdu", comment: "Language"),
    NSLocalizedString("Uyghur", comment: "Language"),
    NSLocalizedString("Uzbek", comment: "Language"),
    NSLocalizedString("Venda", comment: "Language"),
    NSLocalizedString("Venetian", comment: "Language"),
    NSLocalizedString("Veps", comment: "Language"),
    NSLocalizedString("Vietnamese", comment: "Language"),
    NSLocalizedString("Võro", comment: "Language"),
    NSLocalizedString("Votic", comment: "Language"),
    NSLocalizedString("Walloon", comment: "Language"),
    NSLocalizedString("Waray-Waray", comment: "Language"),
    NSLocalizedString("Welsh", comment: "Language"),
    NSLocalizedString("Wiradjuri", comment: "Language"),
    NSLocalizedString("Wolof", comment: "Language"),
    NSLocalizedString("Xamtanga", comment: "Language"),
    NSLocalizedString("Xhosa", comment: "Language"),
    NSLocalizedString("Yagua", comment: "Language"),
    NSLocalizedString("Yi", comment: "Language"),
    NSLocalizedString("Yiddish", comment: "Language"),
    NSLocalizedString("Yindjibarndi", comment: "Language"),
    NSLocalizedString("Yolngu", comment: "Language"),
    NSLocalizedString("Yoruba", comment: "Language"),
    NSLocalizedString("Yupik", comment: "Language"),
    NSLocalizedString("Zhuang", comment: "Language"),
    NSLocalizedString("Zulu", comment: "Language"),
    NSLocalizedString("Zuñi", comment: "Language"),
    
    // Fictional languages
    NSLocalizedString("Quenya", comment: "Language"),
    NSLocalizedString("Sindarin", comment: "Language"),
    NSLocalizedString("Na'vi", comment: "Language"),
    NSLocalizedString("Klingon", comment: "Language"),
    NSLocalizedString("Dovahzul", comment: "Language"),
    NSLocalizedString("Bordurian", comment: "Language"),
    NSLocalizedString("Syldavian", comment: "Language"),
    NSLocalizedString("Kobaïan", comment: "Language"),
    NSLocalizedString("Paku", comment: "Language"),
    NSLocalizedString("Dothraki", comment: "Language"),
    
    // Programming Languages
    "Python",
    "Ruby",
    "JavaScript",
    "C++",
    "C",
    "Shell",
    "C#",
    "PHP",
    "Java",
    "Swift",
    "Kotlin",
    "Perl",
    "Brainfuck",
    "Binary"
]

class World {
    
    internal var continents: [Continent] = []
    internal var languages: [Language] = []
    internal var name: String
    
    func getCountriesOf(_ continent: String) -> [Country]{
        for _continent in continents {
            if _continent.name == continent {
                return _continent.countries
            }
        }
        
        fatalError("No continent found with this name!")
    }
    
    func add(countries: [String], _ continent: String){
        
        let temp_continent = Continent(name: continent)
        
        for country_name in countries{
            let country = Country(name: country_name)
            
            country.flag_name = country_name.lowercased()
            country.flag_name = country.flag_name?.replacingOccurrences(of: " ", with: "-")
            
            temp_continent.countries.append(country)
        }
        
        continents.append(temp_continent)
    }
    
    func add(_ all_languages: [String]) {
        
        for language in all_languages {
            self.languages.append(Language(name: language))
        }
        
    }
    
    //Functionality
    func sortLanguagesAlphabetically(){
        
        self.languages.sort{
            $0.name.localizedCaseInsensitiveCompare($1.name) == ComparisonResult.orderedAscending
        }
        
    }
    
    init(name: String) {
        
        self.name = name
        
        add(countries: countries_africa, NSLocalizedString("Africa", comment: "Continent"))
        add(countries: countries_asia, NSLocalizedString("Asia", comment: "Continent"))
        add(countries: countries_australia_and_oceania, NSLocalizedString("Australia and Oceania", comment: "Continent"))
        add(countries: countries_europe, NSLocalizedString("Europe", comment: "Continent"))
        add(countries: countries_north_america, NSLocalizedString("North America", comment: "Continent"))
        add(countries: countries_south_america, NSLocalizedString("South America", comment: "Continent"))
        
        add(all_languages)
    }
}

class Country {
    internal var name : String? = nil
    internal var spoken_languages : [String] = []
    internal var flag_name : String?
    
    init(name: String) {
        self.name = name
    }
    
    static func countryName(countryCode: String) -> String? {
        let current = Locale(identifier: "en_US")
        return current.localizedString(forRegionCode: countryCode)
    }
}

class Continent {
    internal var name: String
    internal var countries: [Country] = []
    
    init(name: String) {
        self.name = name
    }
}

class Language: Equatable {
    
    internal var name: String = ""
    
    static func == (lhs: Language, rhs: Language) -> Bool {
        return lhs.name == rhs.name
    }
    
    init(name: String) {
        self.name = name
    }
}
