name: Tests

on:
  push:
    branches: [ master, develop, refactor ]
  pull_request:
    branches: [ master, develop, refactor ]

jobs:
  test:
    name: Test
    runs-on: macos-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v1
    - name: Bundle Install
      run: bundle install
    - name: Unit tests
      run: bundle exec fastlane tests
